version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    restart: on-failure
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      SERVER_NAME: "The Wilds"
      LEVEL_NAME: "Wilds"
      ALLOW_CHEATS: "false"
      ENABLE_LAN_VISIBILITY: "false"
      MAX_THREADS: 0
    ports:
      - 19132:19132/udp
    volumes:
      - /azmounts/persistantgamestorage/minecraft-thewilds-data:/data
    stdin_open: true
    tty: true