name: '🎮 Register Discord Commands'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    # paths:
    #   - "Discord/**"
    #   - "!**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  register-commands:
    runs-on: ubuntu-latest
    environment: vs-subscription
    defaults:
      run:
        working-directory: Discord
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Register Commands
      shell: bash
      run: python registerCommands.py