name: 🐳 Valheim Vanilla Image

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "valheim-docker/vanilla/**"
      - "!**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-push-valheim:
    name: Build & Push Valheim Image
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~dockerhub-build-push.yaml@main
    with:
      working-directory: valheim-docker/vanilla
      image-repository: modifamorphic/valheim
      dockerhub-user: ${{ vars.DOCKER_HUB_USER }}
    secrets:
      dockerhub-password: ${{ secrets.DOCKER_HUB_TOKEN }}