# This is a basic workflow to help you get started with Actions

name: 𝙏 keyvault

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "shared/keyvault/**"
      - "!**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  id-token: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  apply-terraform:
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@features/create-tf-actions
    with:
      working-directory: shared/keyvault
      github-environment: vs-subscription
    secrets: inherit