name: '𝙏 Palworld Container Instance'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "container-registries/PalWorld/terraform/**"
      - "!**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  id-token: write

jobs:
  terraform-games-host-vm:
    name: Terraform Palworld Container Instance
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@main
    with:
      working-directory: container-registries/PalWorld/terraform
      github-environment: vs-subscription
      tfvars-file: palworld-server.tfvars
    secrets: inherit
  