# This is a basic workflow to help you get started with Actions

name: 𝙏 Shared Resources

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "features/create-tf-actions" ]
    paths:
      - "shared/**/*.tf"
      - "!**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  id-token: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform-keyvault:
    name: Terraform KeyVault
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@main
    with:
      working-directory: shared/keyvault
      github-environment: vs-subscription
    secrets: inherit
  terraform-vnet:
      name: Terraform Virtual Network
      uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@main
      with:
        working-directory: shared/vnet
        github-environment: vs-subscription
      secrets: inherit
  terraform-nsg:
    name: Terraform Network Security Group
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@main
    with:
      working-directory: shared/nsg
      github-environment: vs-subscription
    secrets: inherit
  terraform-roles:
    name: Terraform Custom Roles
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@main
    with:
      working-directory: shared/roles
      github-environment: vs-subscription
    secrets: inherit
  terraform-scheduler:
    name: Terraform Scheduler Function
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@main
    needs: [ terraform-roles ]
    with:
      working-directory: shared/scheduler/terraform
      github-environment: vs-subscription
    secrets: inherit