# This is a basic workflow to help you get started with Actions

name: 𝙏 vm-games-host

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - "DockerHost/terraform/**"
      - "!**/README.md"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  id-token: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  terraform-games-host-vm:
    name: Terraform VM for Game Hosting
    uses: ModifAmorphic/AzureGameServerContainers/.github/workflows/~terraform-apply.yaml@main
    with:
      working-directory: DockerHost/terraform
      github-environment: vs-subscription
      tfvars-file: vm-games-host.tfvars
    secrets: inherit
  