name: 'Docker Build and Push to DockerHub'

on:
  workflow_call:
    inputs:
      image-repository:
        description: "Repository name of the image to build"
        required: true
        type: string
      working-directory:
        description: "Working directory"
        required: true
        type: string
      dockerhub-user:
        description: "DockerHub User"
        required: true
        type: string
      dockerfile-path:
        description: "Path to the Dockerfile relative to the {{ working-directory }} directory. If not provided, uses {{ working-directory }}/Dockerfile"
        type: string
    secrets:
      
      dockerhub-password:
        description: "DockerHub Password"
        required: true

jobs:
  docker-build-push:
    runs-on: [ ubuntu-latest ]
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:

      - uses: actions/checkout@v3
      
      - name: DockerHub Login
        id: login
        run: echo "${{ secrets.dockerhub-password }}" | docker login -u ${{ inputs.dockerhub-user }} --password-stdin

      - name: Set Environment Variables
        id: set-env-vars
        run: |
          [[ "${{ inputs.dockerfile-path }}" != "" ]] && dockerFile="${{ inputs.dockerfile-path }}" || dockerFile="Dockerfile"
          echo "IMAGE_VERSION_TAG=${{ inputs.image-repository }}:$(date +%s)" >> $GITHUB_ENV
          echo "IMAGE_LATEST_TAG=${{ inputs.image-repository }}:latest" >> $GITHUB_ENV

      - name: Build Image
        id: build
        run: |
          docker build -t $IMAGE_VERSION_TAG -f "$dockerFile" .
          docker tag $IMAGE_VERSION_TAG $IMAGE_LATEST_TAG
      
      - name: Push Image
        id: push
        run: |
          echo "Pushing image with version tag: $IMAGE_VERSION_TAG"
          docker push $IMAGE_VERSION_TAG
          echo "Pushing image with latest tag: $IMAGE_LATEST_TAG"
          docker push $IMAGE_LATEST_TAG

      - name: DockerHub Logout
        if: always()
        id: logout
        run: docker logout
      