name: '~ Terraform Apply'

on:
  workflow_call:
    inputs:
      github-environment:
        description: 'GitHub environment containing AZURE_OIDC_CLIENT_ID, AZURE_SUBSCRIPTION_ID and AZURE_TENANT_ID secrets.'
        type: string
        required: true
      working-directory:
        description: 'Directory terraform commands will be executed in'
        type: string
        required: true
      tfvars-file:
        description: 'Optional path to a terraform .tfvars file, relative to the {working-directory}'
        type: string
        required: false

jobs:
  terraform-apply:
    runs-on: [ ubuntu-latest ]
    environment: ${{ inputs.github-environment }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Environment Variables
        shell: bash
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.AZURE_OIDC_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_USE_OIDC=true" >> $GITHUB_ENV
          varsFile="${{ inputs.tfvars-file }}"
          echo "TFVARS_ARG=${varsFile:+-var-file=$varsFile}" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color $TFVARS_ARG
        continue-on-error: true
      
      - name: Terraform Apply
        id: apply
        run: terraform apply -no-color -auto-approve $TFVARS_ARG